os:
  - linux
services:
  - docker
sudo: required
branches:
  only:
    - master
    - docker_build
cache:
  cargo: true
before_script:
  - docker pull jacderida/crust-ci:0.1.0
script:
  - docker run -v "$PWD":/usr/src/crust jacderida/crust-ci:0.1.0
