env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.29.2
os:
  - linux
language: rust
services:
  - docker
rust:
  - 1.29.2
sudo: required
branches:
  only:
    - master
    - docker_build
cache:
  cargo: true
before_script:
  - docker pull jacderida/crust-ci:0.1.0
script:
  - ls -al
  - docker run -v "$PWD":/usr/src/crust jacderida/crust-ci:0.1.0
before_cache:
  - cargo prune
