env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.29.2
os:
  - linux
  - osx
language: rust
rust:
  - 1.29.2
sudo: false
branches:
  only:
    - master
    - docker
cache:
  cargo: true
before_script:
  - ./scripts/pre-build.sh
script:
  - ./scripts/build.sh
before_cache:
  - cargo prune
